@host = http://localhost:3001

### obtener todos los blogs
GET {{host}}/api/blogs

### obtener blog por id
GET {{host}}/api/blogs/62519bbcc5c6c19704e54490

### eliminar blog por id
DELETE {{host}}/api/blogs/62519bbcc5c6c19704e54490
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbHZpbiIsImlkIjoiNjI0YTU0MDNlZmUwZmQ1OTdjMTE0OWQxIiwiaWF0IjoxNjQ5NTE0MzA2fQ.scGYaCBIgyi5BYYtBxnLu_PCcjVIa40fQh-khuGpKlI


### agregar nuevo blog
POST {{host}}/api/blogs
Content-Type: application/json; charset=utf-8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbHZpbiIsImlkIjoiNjI0YTU0MDNlZmUwZmQ1OTdjMTE0OWQxIiwiaWF0IjoxNjQ5NTE0MzA2fQ.scGYaCBIgyi5BYYtBxnLu_PCcjVIa40fQh-khuGpKlI

{
    "author": "Momo Tik",
    "title": "climated on fired",
    "user": "624a3ad3aadf3db42a03a341",
    "url": "https://techcrunch.com/2022/03/27/fintech-roundup-will-financial-technology-startups-dodge-the-venture-slowdown/",
    "likes": 0
}

### actualizar blog por id
PUT {{host}}/api/blogs/624a4aff70791bda6de4fcaa
Content-Type: application/json; charset=utf-8

{
    "likes": 4
}

