@host = http://localhost:3001
@path = /api/users

### obtener todos los users
GET {{host}}{{path}}

### obtener user por id
GET {{host}}{{path}}/624a46562b40b191e48f0b19

### eliminar user por id
DELETE {{host}}{{path}}/2

### agregar nuevo user
POST {{host}}{{path}}
Content-Type: application/json; charset=utf-8

# {
#     "username": "MarthAZ",
#     "name": "Math Will",
#     "password": "12345678"
# }

# {
#     "username": "dalvin",
#     "name": "Dalvin Molina",
#     "password": "123456"
# }

### actualizar user por id
PUT {{host}}{{path}}/624a46562b40b191e48f0b19
Content-Type: application/json; charset=utf-8

{
    "author": "Mary Ann Merrolan",
    "like": 2
}

